/// Product model representing a seed or fertilizer item.
class Product {
  final String id;
  final String name;
  final String nameMr;
  final String brand;
  final String category; // 'Seeds' or 'Fertilizers'
  final String cropType;
  final String packSize;
  final double price;
  final String imageUrl;
  final String description;
  final String descriptionMr;
  final bool inStock;
  final DateTime createdAt;
  final String companyCity;
  final int minOrder;
  final double packWeight;

  const Product({
    required this.id,
    required this.name,
    required this.nameMr,
    required this.brand,
    required this.category,
    required this.cropType,
    required this.packSize,
    required this.price,
    required this.imageUrl,
    required this.description,
    required this.descriptionMr,
    this.inStock = true,
    required this.createdAt,
    this.companyCity = '',
    this.minOrder = 1,
    this.packWeight = 0.0,
  });

  /// Creates a [Product] from a JSON map.
  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id'] as String,
      name: json['name'] as String,
      nameMr: (json['nameMr'] ?? json['nameHi'] ?? '') as String,
      brand: json['brand'] as String,
      category: json['category'] as String,
      cropType: json['cropType'] as String,
      packSize: json['packSize'] as String,
      price: (json['price'] as num).toDouble(),
      imageUrl: (json['imageUrl'] ?? '') as String,
      description: json['description'] as String,
      descriptionMr: (json['descriptionMr'] ?? json['descriptionHi'] ?? '') as String,
      inStock: json['inStock'] as bool? ?? true,
      createdAt: DateTime.parse(json['createdAt'] as String),
      companyCity: (json['companyCity'] ?? '') as String,
      minOrder: (json['minOrder'] ?? 1) as int,
      packWeight: (json['packWeight'] as num? ?? 0.0).toDouble(),
    );
  }

  /// Serializes this [Product] to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'nameMr': nameMr,
      'brand': brand,
      'category': category,
      'cropType': cropType,
      'packSize': packSize,
      'price': price,
      'imageUrl': imageUrl,
      'description': description,
      'descriptionMr': descriptionMr,
      'inStock': inStock,
      'createdAt': createdAt.toIso8601String(),
      'companyCity': companyCity,
      'minOrder': minOrder,
      'packWeight': packWeight,
    };
  }

  /// Returns a copy of this [Product] with the given fields replaced.
  Product copyWith({
    String? id,
    String? name,
    String? nameMr,
    String? brand,
    String? category,
    String? cropType,
    String? packSize,
    double? price,
    String? imageUrl,
    String? description,
    String? descriptionMr,
    bool? inStock,
    DateTime? createdAt,
    String? companyCity,
    int? minOrder,
    double? packWeight,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      nameMr: nameMr ?? this.nameMr,
      brand: brand ?? this.brand,
      category: category ?? this.category,
      cropType: cropType ?? this.cropType,
      packSize: packSize ?? this.packSize,
      price: price ?? this.price,
      imageUrl: imageUrl ?? this.imageUrl,
      description: description ?? this.description,
      descriptionMr: descriptionMr ?? this.descriptionMr,
      inStock: inStock ?? this.inStock,
      createdAt: createdAt ?? this.createdAt,
      companyCity: companyCity ?? this.companyCity,
      minOrder: minOrder ?? this.minOrder,
      packWeight: packWeight ?? this.packWeight,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Product && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Product(id: $id, name: $name, brand: $brand, ₹$price)';

  /// Returns all 33 sample products.
  static List<Product> getSampleProducts() {
    final now = DateTime.now();
    return [
      Product(
        id: 'SP001',
        name: 'Daftari Agro Rocky Cotton Seeds (BG-2)',
        nameMr: 'दप्तरी अग्रो-रॉकी-कापूस-BG-2',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/4.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 1)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP002',
        name: 'Daftari Agro Pushpa Cotton Seeds (BG-2)',
        nameMr: 'दप्तरी अग्रो-पुष्पा-कापूस-BG-2',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/5.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 2)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP003',
        name: 'Daftari Agro Baban Cotton Seeds (BG-2)',
        nameMr: 'दप्तरी अग्रो-बबन-कापूस-BG-2',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/6.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 3)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP004',
        name: 'Daftari Agro 48 Pigeon Pea Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-48-तूर-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 240.0,
        imageUrl: 'assets/Shantinath Agro Products/7.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 4)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP005',
        name: 'Daftari Agro Gajraj Pigeon Pea Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-Gajraj-तूर-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 240.0,
        imageUrl: '',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 5)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP006',
        name: 'Daftari Agro 48 Gold Pigeon Pea Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-48 गोल्ड-तूर-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 261.0,
        imageUrl: 'assets/Shantinath Agro Products/9.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 6)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP007',
        name: 'Daftari Agro 963 Pigeon Pea Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-963-तूर-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 240.0,
        imageUrl: 'assets/Shantinath Agro Products/10.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 7)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP008',
        name: 'Daftari Agro 345 Pigeon Pea Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-345-तूर-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 240.0,
        imageUrl: 'assets/Shantinath Agro Products/11.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 8)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP009',
        name: 'Daftari Agro 354 Soybean Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-354-सोयाबीन-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3960.0,
        imageUrl: 'assets/Shantinath Agro Products/12.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 9)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP010',
        name: 'Daftari Agro Saniya Soybean Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-सानिया-सोयाबीन-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3750.0,
        imageUrl: 'assets/Shantinath Agro Products/13.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 10)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP011',
        name: 'Daftari Agro Chetak Soybean Seeds (Open)',
        nameMr: 'दप्तरी अग्रो-चेतक-सोयाबीन-Open',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3900.0,
        imageUrl: 'assets/Shantinath Agro Products/14.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 11)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP012',
        name: 'Kohinoor Seeds Mahagun Cotton Seeds (BG-2)',
        nameMr: 'कोहिनूर सीड्स-महागुण-कापूस-BG-2',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/15.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 12)),
        companyCity: 'दिल्ली',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP013',
        name: 'Kohinoor Seeds Dosti Pigeon Pea Seeds (Open)',
        nameMr: 'कोहिनूर सीड्स-दोस्ती-तूर-Open',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 320.0,
        imageUrl: 'assets/Shantinath Agro Products/16.png',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 13)),
        companyCity: 'दिल्ली',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP014',
        name: 'Pravardhan Seeds Axe Cotton Seeds (BG-2)',
        nameMr: 'प्रवर्धन सीड-AXE-कापूस-BG-2',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/17.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 14)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP015',
        name: 'Pravardhan Seeds Revant Cotton Seeds (BG-2)',
        nameMr: 'प्रवर्धन सीड-रेवंत-कापूस-BG-2',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/18.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 15)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP016',
        name: 'Pravardhan Seeds Saubhagya Cotton Seeds (BG-2)',
        nameMr: 'प्रवर्धन सीड-सौभाग्य-कापूस-BG-2',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/19.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 16)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP017',
        name: 'Kurnool Seeds Jai Ho Cotton Seeds (BG-2)',
        nameMr: 'कर्नूल सीड्स-जय हो-कापूस-BG-2',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/20.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 17)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP018',
        name: 'Kurnool Seeds Yoddha Cotton Seeds (BG-2)',
        nameMr: 'कर्नूल सीड्स-योद्धा-कापूस-BG-2',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/21.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 18)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP019',
        name: 'Kurnool Seeds Netaji Cotton Seeds (BG-2)',
        nameMr: 'कर्नूल सीड्स-नेताजी-कापूस-BG-2',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/22.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 19)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP020',
        name: 'Kurnool Seeds Shaho Cotton Seeds (BG-2)',
        nameMr: 'कर्नूल सीड्स-शाहो-कापूस-BG-2',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/23.png',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 20)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP021',
        name: 'Palmor Seeds Dhamaka Cotton Seeds (BG-2)',
        nameMr: 'पालमोर सीड-धमाका-कापूस-BG-2',
        brand: 'Palmor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/24.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 21)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP022',
        name: 'Palmor Seeds Bahadur Cotton Seeds (BG-2)',
        nameMr: 'पालमोर सीड-बहादूर-कापूस-BG-2',
        brand: 'Palmor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/25.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 22)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP023',
        name: 'Palmor Seeds Shindur Cotton Seeds (BG-2)',
        nameMr: 'पालमोर सीड-शिंदूर-कापूस-BG-2',
        brand: 'Palmor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/26.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 23)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP024',
        name: 'Palmor Seeds PRG-100 Pigeon Pea Seeds (Open)',
        nameMr: 'पालमोर सीड-PRG-100-तूर-Open',
        brand: 'Palmor Seeds',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 260.0,
        imageUrl: 'assets/Shantinath Agro Products/27.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 24)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP025',
        name: 'Tata Rallis Bigex 7388 Cotton Seeds (BG-2)',
        nameMr: 'टाटा रॅलीस-बिगेक्स 7388-कापूस-BG-2',
        brand: 'Tata Rallis',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/28.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 25)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP026',
        name: 'Alpagari Seeds Volvo Cotton Seeds (BG-2)',
        nameMr: 'अल्पगरी सीड-वोल्वो-कापूस-BG-2',
        brand: 'Alpagari Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/29.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 26)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP027',
        name: 'Alpagari Seeds Total Cotton Seeds (BG-2)',
        nameMr: 'अल्पगरी सीड-टोटल-कापूस-BG-2',
        brand: 'Alpagari Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '0.475 kg packet',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/30.jpg',
        description: 'High yielding BG-2 Bt cotton hybrid seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतीचे बीजी-२ संकरित कापूस बियाणे. भरपूर उत्पादन आणि कीड-रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 27)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP028',
        name: 'Green Gold Seeds Toor Gold 100 Pigeon Pea Seeds (Open)',
        nameMr: 'Green गोल्ड सीड्स-तूर गोल्ड-100-तूर-Open',
        brand: 'Green Gold Seeds',
        category: 'Seeds',
        cropType: 'Pigeon Pea',
        packSize: '1 kg packet',
        price: 283.0,
        imageUrl: 'assets/Shantinath Agro Products/31.jpg',
        description: 'Premium quality Pigeon Pea seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 28)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP029',
        name: 'Green Gold Seeds 3344 Soybean Seeds (Open)',
        nameMr: 'Green गोल्ड सीड्स-3344-सोयाबीन-Open',
        brand: 'Green Gold Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3600.0,
        imageUrl: 'assets/Shantinath Agro Products/32.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 29)),
        companyCity: 'संभाजीनगर',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP030',
        name: 'Green Gold Seeds 301 Soybean Seeds (Open)',
        nameMr: 'Green गोल्ड सीड्स-301-सोयाबीन-Open',
        brand: 'Green Gold Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3500.0,
        imageUrl: 'assets/Shantinath Agro Products/33.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 30)),
        companyCity: 'संभाजीनगर',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP031',
        name: 'Rishikesh Seeds Mahashakti Soybean Seeds (Open)',
        nameMr: 'ऋषिकेश सीड्स-महाशक्ती-सोयाबीन-Open',
        brand: 'Rishikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25 kg bag',
        price: 2775.0,
        imageUrl: 'assets/Shantinath Agro Products/34.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 31)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP032',
        name: 'Rishikesh Seeds R-Kabaddi Soybean Seeds (Open)',
        nameMr: 'ऋषिकेश सीड्स-R-कबड्डी-सोयाबीन-Open',
        brand: 'Rishikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25 kg bag',
        price: 2775.0,
        imageUrl: 'assets/Shantinath Agro Products/35.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 32)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP033',
        name: 'Rishikesh Seeds JS-9305 Soybean Seeds (Open)',
        nameMr: 'ऋषिकेश सीड्स-JS-9305-सोयाबीन-Open',
        brand: 'Rishikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30 kg bag',
        price: 3030.0,
        imageUrl: 'assets/Shantinath Agro Products/36.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 33)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 30.0,
      ),
    ];
  }
}
