import 'package:cloud_firestore/cloud_firestore.dart';

/// Product model representing a seed or fertilizer item.
class Product {
  final String id;
  final String name;
  final String nameMr;
  final String brand;
  final String category; // 'Seeds' or 'Fertilizers'
  final String cropType;
  final String packSize;
  final double price;
  final String imageUrl;
  final String description;
  final String descriptionMr;
  final bool inStock;
  final DateTime createdAt;
  final String companyCity;
  final int minOrder;
  final double packWeight;
  final bool isFeatured;
  final bool isVisible;

  const Product({
    required this.id,
    required this.name,
    required this.nameMr,
    required this.brand,
    required this.category,
    required this.cropType,
    required this.packSize,
    required this.price,
    required this.imageUrl,
    required this.description,
    required this.descriptionMr,
    this.inStock = true,
    required this.createdAt,
    this.companyCity = '',
    this.minOrder = 1,
    this.packWeight = 0.0,
    this.isFeatured = false,
    this.isVisible = true,
  });

  /// Creates a [Product] from a JSON map.
  factory Product.fromJson(Map<String, dynamic> json) {
    DateTime parsedDate;
    if (json['createdAt'] is Timestamp) {
      parsedDate = (json['createdAt'] as Timestamp).toDate();
    } else if (json['createdAt'] is String) {
      parsedDate = DateTime.tryParse(json['createdAt'] as String) ?? DateTime.now();
    } else {
      parsedDate = DateTime.now();
    }

    return Product(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      nameMr: (json['nameMr'] ?? json['nameHi'] ?? '') as String,
      brand: json['brand'] as String? ?? '',
      category: json['category'] as String? ?? '',
      cropType: json['cropType'] as String? ?? '',
      packSize: json['packSize'] as String? ?? '',
      price: (json['price'] as num?)?.toDouble() ?? 0.0,
      imageUrl: (json['imageUrl'] ?? '') as String,
      description: json['description'] as String? ?? '',
      descriptionMr: (json['descriptionMr'] ?? json['descriptionHi'] ?? '') as String,
      inStock: json['inStock'] as bool? ?? true,
      createdAt: parsedDate,
      companyCity: (json['companyCity'] ?? '') as String,
      minOrder: (json['minOrder'] as num?)?.toInt() ?? 1,
      packWeight: (json['packWeight'] as num? ?? 0.0).toDouble(),
      isFeatured: json['isFeatured'] as bool? ?? false,
      isVisible: json['isVisible'] as bool? ?? true,
    );
  }

  /// Serializes this [Product] to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'nameMr': nameMr,
      'brand': brand,
      'category': category,
      'cropType': cropType,
      'packSize': packSize,
      'price': price,
      'imageUrl': imageUrl,
      'description': description,
      'descriptionMr': descriptionMr,
      'inStock': inStock,
      'createdAt': createdAt.toIso8601String(),
      'companyCity': companyCity,
      'minOrder': minOrder,
      'packWeight': packWeight,
      'isFeatured': isFeatured,
      'isVisible': isVisible,
    };
  }

  /// Returns a copy of this [Product] with the given fields replaced.
  Product copyWith({
    String? id,
    String? name,
    String? nameMr,
    String? brand,
    String? category,
    String? cropType,
    String? packSize,
    double? price,
    String? imageUrl,
    String? description,
    String? descriptionMr,
    bool? inStock,
    DateTime? createdAt,
    String? companyCity,
    int? minOrder,
    double? packWeight,
    bool? isFeatured,
    bool? isVisible,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      nameMr: nameMr ?? this.nameMr,
      brand: brand ?? this.brand,
      category: category ?? this.category,
      cropType: cropType ?? this.cropType,
      packSize: packSize ?? this.packSize,
      price: price ?? this.price,
      imageUrl: imageUrl ?? this.imageUrl,
      description: description ?? this.description,
      descriptionMr: descriptionMr ?? this.descriptionMr,
      inStock: inStock ?? this.inStock,
      createdAt: createdAt ?? this.createdAt,
      companyCity: companyCity ?? this.companyCity,
      minOrder: minOrder ?? this.minOrder,
      packWeight: packWeight ?? this.packWeight,
      isFeatured: isFeatured ?? this.isFeatured,
      isVisible: isVisible ?? this.isVisible,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Product && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Product(id: $id, name: $name, brand: $brand, ₹$price)';

  /// Returns all 33 sample products.
  static List<Product> getSampleProducts() {
    final now = DateTime.now();
    return [
      Product(
        id: 'SP001',
        name: 'DAFTARI - ROCKY BG-II 3434 HY',
        nameMr: 'दप्तरी - रॉकी बीजी-२ ३४३४ एचवाय',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/4.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 1)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475, isFeatured: true,
      ),
      Product(
        id: 'SP002',
        name: 'DAFTARI - PUSHPA BG-II 7004 HY',
        nameMr: 'दप्तरी - पुष्पा बीजी-२ ७००४ एचवाय',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/5.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 2)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP003',
        name: 'DAFTARI - BABAN BG-II 2434 HY',
        nameMr: 'दप्तरी - बबन बीजी-२ २४३४ एचवाय',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/6.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 3)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP004',
        name: 'TUV DAFTARI-48 (DAFTARI) 2KG',
        nameMr: 'तूर दप्तरी-४८ (दप्तरी) २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 480.0,
        imageUrl: 'assets/Shantinath Agro Products/7.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 4)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP005',
        name: 'TUV DPL-848 (DAFTARI) 2KG',
        nameMr: 'तूर डीपीएल-८४८ (दप्तरी) २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 240.0,
        imageUrl: '',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 5)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP006',
        name: 'TUV UAJWAL (DAFTARI) 2 KG',
        nameMr: 'तूर उज्ज्वल (दप्तरी) २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 261.0,
        imageUrl: 'assets/Shantinath Agro Products/9.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 6)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP007',
        name: 'TUV PRG 163 [WFT] 2KG',
        nameMr: 'तूर पीआरजी १६३ [डब्ल्यूएफटी] २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 240.0,
        imageUrl: 'assets/Shantinath Agro Products/10.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 7)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP008',
        name: 'TUV DAFTARI MARUTHI (DAFTARI) 2KG',
        nameMr: 'तूर दप्तरी मारुती (दप्तरी) २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 250.0,
        imageUrl: 'assets/Shantinath Agro Products/11.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 8)),
        companyCity: 'शेलू',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP009',
        name: 'DAFTARI SOYABEEN -335 30KG',
        nameMr: 'दप्तरी सोयाबीन -३३५ ३०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 3960.0,
        imageUrl: 'assets/Shantinath Agro Products/12.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 9)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0, isFeatured: true,
      ),
      Product(
        id: 'SP010',
        name: 'DAFTARI SOYABEEN -SAMRAT-YL 30KG',
        nameMr: 'दप्तरी सोयाबीन -सम्राट-वाईएल ३०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 3750.0,
        imageUrl: 'assets/Shantinath Agro Products/13.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 10)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP011',
        name: 'DAFTARI SOYABEEN CHETAK - YL 30 KG',
        nameMr: 'दप्तरी सोयाबीन चेतक - वायएल ३० किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 3900.0,
        imageUrl: 'assets/Shantinath Agro Products/14.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 11)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP012',
        name: 'MAHAGUN (KSC) 225 BGM COTTON 475GM',
        nameMr: 'महागुण (केएससी) २२५ बीजीएम कापूस ४७५ग्रॅम',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/15.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 12)),
        companyCity: 'दिल्ली',
        minOrder: 30,
        packWeight: 0.475, isFeatured: true,
      ),
      Product(
        id: 'SP013',
        name: 'RED GRAM SEEDS DOSTI (KSC) (1+1) 1 KG KIT',
        nameMr: 'तूर बियाणे दोस्ती (केएससी) (१+१) १ किलो किट',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '1KG KIT',
        price: 320.0,
        imageUrl: 'assets/Shantinath Agro Products/16.png',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 13)),
        companyCity: 'दिल्ली',
        minOrder: 30,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP014',
        name: 'AJID PSH-221 BG-II [PRAVARDHAN] 450GM',
        nameMr: 'अजीद पीएसएच-२२१ बीजी-२ [प्रवर्धन] ४५०ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '450GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/17.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 14)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.45,
      ),
      Product(
        id: 'SP015',
        name: 'REGAL PRCH-721 BG-II 475 GM',
        nameMr: 'रीगल पीआरसीएच-७२१ बीजी-२ ४७५ ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/18.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 15)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP016',
        name: 'SURNAVILIYA [MCH-004 BG-II] [PRAVARDHAN] 475GM',
        nameMr: 'सूर्याविलीया [एमसीएच-००४ बीजी-२] [प्रवर्धन] ४७५ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/19.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 16)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP017',
        name: 'JAYHO NY COTTON (KEC-1658 BG-II) 475GM',
        nameMr: 'जयहो एनवाय कापूस (केईसी-१६५८ बीजी-२) ४७५ग्रॅम',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/20.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 17)),
        companyCity: 'कर्नूल',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP018',
        name: 'YOONA NY COTTON (KEC-1658 BG-II) 475 GM',
        nameMr: 'युना एनवाय कापूस (केईसी-१६५८ बीजी-२) ४७५ ग्रॅम',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/21.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 18)),
        companyCity: 'कर्नूल',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP019',
        name: 'NETRAWATI COTTON GOLD (KEC-1602 BG-II) 475 GM',
        nameMr: 'नेत्रवती कापूस गोल्ड (केईसी-१६०२ बीजी-२) ४७५ ग्रॅम',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/22.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 19)),
        companyCity: 'कर्नूल',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP020',
        name: 'SAAHU NY COTTON (KEC-1658 BG-II) 475 GM',
        nameMr: 'शाहू एनवाय कापूस (केईसी-१६५८ बीजी-२) ४७५ ग्रॅम',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/23.png',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 20)),
        companyCity: 'कर्नूल',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP021',
        name: 'BHAKNA BG-II (KSH-602 BG-II) 450GM',
        nameMr: 'भाकणा बीजी-२ (केएसएच-६०२ बीजी-२) ४५०ग्रॅम',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '450GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/24.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 21)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.45,
      ),
      Product(
        id: 'SP022',
        name: 'BAJRA BH-31 (PALMOOR) 1.5 KG',
        nameMr: 'बाजरी बीएच-३१ (पालमूर) १.५ किलो',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Bajra',
        packSize: '1.5KG',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/25.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 22)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 1.5,
      ),
      Product(
        id: 'SP023',
        name: 'BAJRA PLH-44 BG-II (PALMOOR) 450 GM',
        nameMr: 'बाजरी पीएलएच-४४ बीजी-२ (पालमूर) ४५० ग्रॅम',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Bajra',
        packSize: '450GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/26.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 23)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.45,
      ),
      Product(
        id: 'SP024',
        name: 'TUV REDGRAM PRG-162 (PALMOOR) 2KG',
        nameMr: 'तूर रेडग्राम पीआरजी-१६२ (पालमूर) २किलो',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 260.0,
        imageUrl: 'assets/Shantinath Agro Products/27.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 24)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP025',
        name: 'RHDX-082 BG-II 475 GM RALLIES',
        nameMr: 'आरएचडीएक्स-०८२ बीजी-२ ४७५ ग्रॅम रॅलीज',
        brand: 'Rallies Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/28.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 25)),
        companyCity: 'मुंबई',
        minOrder: 30,
        packWeight: 0.475, isFeatured: true,
      ),
      Product(
        id: 'SP026',
        name: 'VOLVO PLUS BG-II COTTON 475GM',
        nameMr: 'वोल्वो प्लस बीजी-२ कापूस ४७५ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/29.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 26)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP027',
        name: 'TOTAL BG-II (A-PACHTI) 475 GM',
        nameMr: 'टोटल बीजी-२ (ए-पाचटी) ४७५ ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 901.0,
        imageUrl: 'assets/Shantinath Agro Products/30.jpg',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 27)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP028',
        name: 'TUV GOLD-148 (GREENGOLD) 2KG',
        nameMr: 'तूर गोल्ड-१४८ (ग्रीनगोल्ड) २किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 283.0,
        imageUrl: 'assets/Shantinath Agro Products/31.jpg',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 28)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP029',
        name: 'SOYABEEN GOLD-335 (GG) 25KG',
        nameMr: 'सोयाबीन गोल्ड-३३५ (जीजी) २५किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 3600.0,
        imageUrl: 'assets/Shantinath Agro Products/32.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 29)),
        companyCity: 'संभाजीनगर',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP030',
        name: 'SOYABEEN GOLD-305 (GG) 25 KG',
        nameMr: 'सोयाबीन गोल्ड-३०५ (जीजी) २५ किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 3500.0,
        imageUrl: 'assets/Shantinath Agro Products/33.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 30)),
        companyCity: 'संभाजीनगर',
        minOrder: 1,
        packWeight: 25.0, isFeatured: true,
      ),
      Product(
        id: 'SP031',
        name: 'SOYABEAN MAHASHAKTI-335 Y.L. 25 KG',
        nameMr: 'सोयाबीन महाशक्ती-३३५ वाय.एल. २५ किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 2775.0,
        imageUrl: 'assets/Shantinath Agro Products/34.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 31)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP032',
        name: 'SOYABEAN KABULI 2172 J.L. 25 KG',
        nameMr: 'सोयाबीन काबुली २१७२ जे.एल. २५ किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 2775.0,
        imageUrl: 'assets/Shantinath Agro Products/35.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 32)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP033',
        name: 'SOYABEAN JS3305 C/F [RUSHIKESH] 30KG',
        nameMr: 'सोयाबीन जेएस३३०५ सी/एफ [ऋषिकेश] ३०किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 3030.0,
        imageUrl: 'assets/Shantinath Agro Products/36.jpg',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 33)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 30.0, isFeatured: true,
      ),
      Product(
        id: 'SP034',
        name: 'SSP POWDER PACKED 50KG',
        nameMr: 'एसएसपी पावडर पॅक्ड ५०किलो',
        brand: 'Del Super',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 580.0,
        imageUrl: '',
        description: 'Premium quality Single Super Phosphate (SSP) Powder fertilizer. Rich in phosphorus and sulphur.',
        descriptionMr: 'उत्कृष्ट दर्जाचे सिंगल सुपर फॉस्फेट (एसएसपी) पावडर खत. फॉस्फरस आणि सल्फरने समृद्ध.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 34)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0, isFeatured: true,
      ),
      Product(
        id: 'SP035',
        name: 'SSP GRANULAR PACKED 50 KG',
        nameMr: 'एसएसपी दाणेदार पॅक्ड ५० किलो',
        brand: 'Del Super',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 630.0,
        imageUrl: '',
        description: 'Premium quality Single Super Phosphate (SSP) Granular fertilizer. Rich in phosphorus and sulphur.',
        descriptionMr: 'उत्कृष्ट दर्जाचे सिंगल सुपर फॉस्फेट (एसएसपी) दाणेदार खत. फॉस्फरस आणि सल्फरने समृद्ध.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 35)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0, isFeatured: true,
      ),
      Product(
        id: 'SP036',
        name: 'SSP ZINC POWDER PACKED 50 KG',
        nameMr: 'एसएसपी झिंक पावडर पॅक्ड ५० किलो',
        brand: 'Del Super',
        category: 'Fertilizers',
        cropType: 'Cotton',
        packSize: '50KG',
        price: 600.0,
        imageUrl: '',
        description: 'Zincated Single Super Phosphate Powder. Contains essential zinc micronutrients along with phosphorus and sulphur.',
        descriptionMr: 'झिंकयुक्त सिंगल सुपर फॉस्फेट पावडर खत. फॉस्फरस आणि सल्फरसोबत आवश्यक झिंक सूक्ष्मद्रव्य समाविष्ट.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 36)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP037',
        name: 'SSP ZINC GRANULAR PACKED 50KG',
        nameMr: 'एसएसपी झिंक दाणेदार पॅक्ड ५०किलो',
        brand: 'Del Super',
        category: 'Fertilizers',
        cropType: 'Cotton',
        packSize: '50KG',
        price: 650.0,
        imageUrl: '',
        description: 'Zincated Single Super Phosphate Granular. Contains essential zinc micronutrients along with phosphorus and sulphur.',
        descriptionMr: 'झिंकयुक्त सिंगल सुपर फॉस्फेट दाणेदार खत. फॉस्फरस आणि सल्फरसोबत आवश्यक झिंक सूक्ष्मद्रव्य समाविष्ट.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 37)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP038',
        name: 'SSP ZINC BORON GRANULAR 50KG',
        nameMr: 'एसएसपी झिंक बोरॉन दाणेदार ५०किलो',
        brand: 'Del Super',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 780.0,
        imageUrl: '',
        description: 'Zincated and Boronated Single Super Phosphate Granular fertilizer. Contains zinc and boron micronutrients along with phosphorus and sulphur.',
        descriptionMr: 'झिंक आणि बोरॉनयुक्त सिंगल सुपर फॉस्फेट दाणेदार खत. फॉस्फरस आणि सल्फरसोबत झिंक व बोरॉन सूक्ष्मद्रव्ये समाविष्ट.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 38)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP039',
        name: 'KRUSHIRAJA NPK-18-18-10[50KG]',
        nameMr: 'कृषिराजा एनपीके-१८-१८-१०[५०किलो]',
        brand: 'Greenfield',
        category: 'Fertilizers',
        cropType: 'Cotton',
        packSize: '50KG',
        price: 1350.0,
        imageUrl: '',
        description: 'High quality NPK complex fertilizer. Balanced nutrition for all types of crops.',
        descriptionMr: 'उत्कृष्ट दर्जाचे एनपीके संयुक्त खत. सर्व प्रकारच्या पिकांसाठी संतुलित पोषण.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 39)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0, isFeatured: true,
      ),
      Product(
        id: 'SP040',
        name: 'AJID 21 BG-II COTTON 475GM',
        nameMr: 'अजीद २१ बीजी-२ कापूस ४७५ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 40)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP041',
        name: 'NAMDCOT(927) - VOLVO PLUS 475GM',
        nameMr: 'नॅमडकॉट (९२७) - वोल्वो प्लस ४७५ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 41)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP042',
        name: 'SOLAR 55 BG-II (V-I) [VO 29 PL] 475 GMS',
        nameMr: 'सोलर ५५ बीजी-२ (व्ही-१) [व्हीओ २९ पीएल] ४७५ ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 42)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP043',
        name: 'SOLAR 77 BG-II (ROBOT) 475 GM',
        nameMr: 'सोलर ७७ बीजी-२ (रोबोट) ४७५ ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 43)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP044',
        name: 'SOLAR 77 BG-II (SUPER TOTAL) 475 GM',
        nameMr: 'सोलर ७७ बीजी-२ (सुपर टोटल) ४७५ ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 44)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP045',
        name: 'SOLAR 99 BG-II (AGNI PLUS) 475 GM',
        nameMr: 'सोलर ९९ बीजी-२ (अग्नी प्लस) ४७५ ग्रॅम',
        brand: 'Alpagiri Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 45)),
        companyCity: 'अहमदाबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP046',
        name: 'GOLDCOT BG-II NG8864 475 GM',
        nameMr: 'गोल्डकॉट बीजी-२ एनजी८८६४ ४७५ ग्रॅम',
        brand: 'Asian Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 800.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 46)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP047',
        name: 'SIMRAN BG-II (ASIAN) 450GM',
        nameMr: 'सिमरन बीजी-२ (एशियन) ४५०ग्रॅम',
        brand: 'Asian Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '450GM',
        price: 800.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 47)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 0.45,
      ),
      Product(
        id: 'SP048',
        name: 'DAFTARI - JEED BG-II HY',
        nameMr: 'दप्तरी - जीद बीजी-२ एचवाय',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 880.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 48)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP049',
        name: 'CHILLY DHARUM (DAFTARI) 10GM',
        nameMr: 'मिरची धरम (दप्तरी) १०ग्रॅम',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Chilly',
        packSize: '10GM',
        price: 120.0,
        imageUrl: '',
        description: 'High yielding hybrid Chilly seeds. Excellent pungency and fruit quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मिरची बियाणे. तिखटपणा आणि चांगल्या दर्जाची फळे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 49)),
        companyCity: 'शेलू',
        minOrder: 10,
        packWeight: 0.01,
      ),
      Product(
        id: 'SP050',
        name: 'CHILLY MORIA-127 (DAFTARI) 10GM',
        nameMr: 'मिरची मोरिया-१२७ (दप्तरी) १०ग्रॅम',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Chilly',
        packSize: '10GM',
        price: 130.0,
        imageUrl: '',
        description: 'High yielding hybrid Chilly seeds. Excellent pungency and fruit quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मिरची बियाणे. तिखटपणा आणि चांगल्या दर्जाची फळे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 50)),
        companyCity: 'शेलू',
        minOrder: 10,
        packWeight: 0.01,
      ),
      Product(
        id: 'SP051',
        name: 'FODDER 888 (DAFTARI) 3KG',
        nameMr: 'चारा ८८८ (दप्तरी) ३किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Fodder',
        packSize: '3KG',
        price: 450.0,
        imageUrl: '',
        description: 'High nutritional value Fodder seeds. Excellent regrowth and biomass.',
        descriptionMr: 'पोषक गुणांनी समृद्ध चारा बियाणे. जलद वाढ आणि दर्जेदार चारा.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 51)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 3.0,
      ),
      Product(
        id: 'SP052',
        name: 'FODDER DFSH-895 (DAFTARI) 4KG',
        nameMr: 'चारा डीएफएसएच-८९५ (दप्तरी) ४किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Fodder',
        packSize: '4KG',
        price: 600.0,
        imageUrl: '',
        description: 'High nutritional value Fodder seeds. Excellent regrowth and biomass.',
        descriptionMr: 'पोषक गुणांनी समृद्ध चारा बियाणे. जलद वाढ आणि दर्जेदार चारा.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 52)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 4.0,
      ),
      Product(
        id: 'SP053',
        name: 'GRAM DAFTARI-21 10 KG',
        nameMr: 'हरभरा दप्तरी-२१ १०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1200.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 53)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP054',
        name: 'GRAM DAFTARI-21 10KG',
        nameMr: 'हरभरा दप्तरी-२१ १०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1200.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 54)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP055',
        name: 'GRAM DAFTARI-31 10KG',
        nameMr: 'हरभरा दप्तरी-३१ १०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1200.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 55)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP056',
        name: 'GRAM DAFTARI-51 10 KG',
        nameMr: 'हरभरा दप्तरी-५१ १० किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1200.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 56)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP057',
        name: 'GRAM PKV-KAK-2 (DAFTARI) 20KG',
        nameMr: 'हरभरा पीकेव्ही-काक-२ (दप्तरी) २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '20KG',
        price: 1250.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 57)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP058',
        name: 'GROUNDNUT DAFTARI-95 20KG',
        nameMr: 'भुईमूग दप्तरी-९५ २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Groundnut',
        packSize: '20KG',
        price: 2200.0,
        imageUrl: '',
        description: 'High oil yield variety Groundnut seeds. Excellent germination and bold pods.',
        descriptionMr: 'तेलाचे जास्त प्रमाण असलेले भुईमूग बियाणे. टपोरे दाणे आणि चांगली उगवण क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 58)),
        companyCity: 'शेलू',
        minOrder: 2,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP059',
        name: 'GROUNDNUT TAG-24 (DAFTARI) 20KG',
        nameMr: 'भुईमूग टीएजी-२४ (दप्तरी) २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Groundnut',
        packSize: '20KG',
        price: 2100.0,
        imageUrl: '',
        description: 'High oil yield variety Groundnut seeds. Excellent germination and bold pods.',
        descriptionMr: 'तेलाचे जास्त प्रमाण असलेले भुईमूग बियाणे. टपोरे दाणे आणि चांगली उगवण क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 59)),
        companyCity: 'शेलू',
        minOrder: 2,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP060',
        name: 'JOWAR DSH-459 (DAFTARI) 3KG',
        nameMr: 'ज्वारी डीएसएच-४५९ (दप्तरी) ३किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Jowar',
        packSize: '3KG',
        price: 500.0,
        imageUrl: '',
        description: 'Premium quality Jowar seeds. High fodder yield and grain quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे ज्वारी बियाणे. चारा आणि धान्याचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 60)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 3.0,
      ),
      Product(
        id: 'SP061',
        name: 'JOWAR DSV-120 (DAFTARI) 3KG',
        nameMr: 'ज्वारी डीएसव्ही-१२० (दप्तरी) ३किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Jowar',
        packSize: '3KG',
        price: 900.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 61)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 3.0,
      ),
      Product(
        id: 'SP062',
        name: 'JOWAR M-35-1 MALDANDI (DAFTARI) 4KG',
        nameMr: 'ज्वारी एम-३५-१ मालदंडी (दप्तरी) ४किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Jowar',
        packSize: '4KG',
        price: 950.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 62)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 4.0,
      ),
      Product(
        id: 'SP063',
        name: 'MOONG S-9/ANILA (DAFTARI) 3KG',
        nameMr: 'मूग एस-९/अनिला (दप्तरी) ३किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Mung',
        packSize: '3KG',
        price: 920.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 63)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 3.0,
      ),
      Product(
        id: 'SP064',
        name: 'DAFTARI SOYABEEN -777 20KG',
        nameMr: 'दप्तरी सोयाबीन -७७७ २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '20KG',
        price: 3800.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 64)),
        companyCity: 'शेलू',
        minOrder: 1,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP065',
        name: 'TIL SESAMUM D-22 (DAFTARI) 500GM',
        nameMr: 'तीळ तीळ-२२ (दप्तरी) ५००ग्रॅम',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Sesame',
        packSize: '500GM',
        price: 250.0,
        imageUrl: '',
        description: 'High oil content Sesame seeds. Excellent purity and yield.',
        descriptionMr: 'तेलाचे जास्त प्रमाण असलेले तीळ बियाणे. उत्तम शुद्धता आणि अधिक उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 65)),
        companyCity: 'शेलू',
        minOrder: 10,
        packWeight: 0.5,
      ),
      Product(
        id: 'SP066',
        name: 'TIL SESAMUM O-31 (DAFTARI) 500GM',
        nameMr: 'तीळ ओ-३१ (दप्तरी) ५००ग्रॅम',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Sesame',
        packSize: '500GM',
        price: 450.0,
        imageUrl: '',
        description: 'High oil content Sesame seeds. Excellent purity and yield.',
        descriptionMr: 'तेलाचे जास्त प्रमाण असलेले तीळ बियाणे. उत्तम शुद्धता आणि अधिक उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 66)),
        companyCity: 'शेलू',
        minOrder: 10,
        packWeight: 0.5,
      ),
      Product(
        id: 'SP067',
        name: 'WHEAT DAFTARI-1 20KG',
        nameMr: 'गहू दप्तरी-१ २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 950.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 67)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP068',
        name: 'WHEAT DAFTARI-21 [PDKV]',
        nameMr: 'गहू दप्तरी-२१ [पीडीकेव्ही]',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 950.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 68)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP069',
        name: 'WHEAT DAFTARI-9 20KG',
        nameMr: 'गहू दप्तरी-९ २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 950.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 69)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP070',
        name: 'WHEAT DAFTARI VIJAYAK-51 20KG',
        nameMr: 'गहू दप्तरी विजयाक-५१ २०किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 1000.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 70)),
        companyCity: 'शेलू',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP071',
        name: 'COWPEA GOLD-305 (GG) 500GM',
        nameMr: 'चवळी गोल्ड-३०५ (जीजी) ५००ग्रॅम',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Cowpea',
        packSize: '500GM',
        price: 100.0,
        imageUrl: '',
        description: 'Premium quality Cowpea seeds. Excellent branching and pod yield.',
        descriptionMr: 'दर्जेदार चवळी बियाणे. अधिक फांद्या आणि शेंगांचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 71)),
        companyCity: 'संभाजीनगर',
        minOrder: 10,
        packWeight: 0.5,
      ),
      Product(
        id: 'SP072',
        name: 'GRAM COLL-272 (GREENGOLD) 10KG',
        nameMr: 'हरभरा कॉल-२७२ (ग्रीनगोल्ड) १०किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1400.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 72)),
        companyCity: 'संभाजीनगर',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP073',
        name: 'GRAM GOLD-25 (GREENGOLD) 10KG',
        nameMr: 'हरभरा गोल्ड-२५ (ग्रीनगोल्ड) १०किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Gram',
        packSize: '10KG',
        price: 1300.0,
        imageUrl: '',
        description: 'Premium quality Gram seeds. High yield and uniform grain size.',
        descriptionMr: 'दर्जेदार हरभरा बियाणे. भरपूर उत्पादन आणि एकसारखे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 73)),
        companyCity: 'संभाजीनगर',
        minOrder: 5,
        packWeight: 10.0,
      ),
      Product(
        id: 'SP074',
        name: 'KANAK GBH-9010 (GG) 475 GM',
        nameMr: 'कनक जीबीएच-९०१० (जीजी) ४७५ ग्रॅम',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 860.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 74)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP075',
        name: 'KUBER GBH-35 BG-II (GG) 475GM',
        nameMr: 'कुबेर जीबीएच-३५ बीजी-२ (जीजी) ४७५ग्रॅम',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 880.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 75)),
        companyCity: 'संभाजीनगर',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP076',
        name: 'MOONG GOLD-9 SHANESHWARI (GREENGOLD) 1KG',
        nameMr: 'मूग गोल्ड-९ ज्ञानेश्वरी (ग्रीनगोल्ड) १किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Mung',
        packSize: '1KG',
        price: 220.0,
        imageUrl: '',
        description: 'High yield Mung seeds. Uniform maturity and disease resistance.',
        descriptionMr: 'भरपूर उत्पादन देणारे मूग बियाणे. एकसमान पक्वता आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 76)),
        companyCity: 'संभाजीनगर',
        minOrder: 10,
        packWeight: 1.0,
      ),
      Product(
        id: 'SP077',
        name: 'SOYABEEN GOLD-JAYAL (GG) 25KG',
        nameMr: 'सोयाबीन गोल्ड-जायल (जीजी) २५किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 3700.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 77)),
        companyCity: 'संभाजीनगर',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP078',
        name: 'TIL SESAME GOLD-101 GAGANPATRI (GG) 500GM',
        nameMr: 'तीळ गोल्ड-१०१ गगनपत्री (जीजी) ५००ग्रॅम',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Sesame',
        packSize: '500GM',
        price: 480.0,
        imageUrl: '',
        description: 'High oil content Sesame seeds. Excellent purity and yield.',
        descriptionMr: 'तेलाचे जास्त प्रमाण असलेले तीळ बियाणे. उत्तम शुद्धता आणि अधिक उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 78)),
        companyCity: 'संभाजीनगर',
        minOrder: 10,
        packWeight: 0.5,
      ),
      Product(
        id: 'SP079',
        name: 'WHEAT GOLD-21 (GG) 20 KG',
        nameMr: 'गहू गोल्ड-२१ (जीजी) २० किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 1050.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 79)),
        companyCity: 'संभाजीनगर',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP080',
        name: 'WHEAT GOLD-32 (GG) 20KG',
        nameMr: 'गहू गोल्ड-३२ (जीजी) २०किलो',
        brand: 'Greengold Seeds',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 1050.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 80)),
        companyCity: 'संभाजीनगर',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP081',
        name: 'TADAARKA COTTON (KSH-302 BG-II) KOHINOOR 475 GM',
        nameMr: 'तदारका कापूस (केएसएच-३०२ बीजी-२) कोहिनूर ४७५ ग्रॅम',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 81)),
        companyCity: 'दिल्ली',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP082',
        name: 'WHEAT SEEDS KWA-14 (KOHINOOR) 20 KG',
        nameMr: 'गहू बियाणे केडब्ल्यूए-१४ (कोहिनूर) २० किलो',
        brand: 'Kohinoor Seeds',
        category: 'Seeds',
        cropType: 'Wheat',
        packSize: '20KG',
        price: 980.0,
        imageUrl: '',
        description: 'High yield variety Wheat seeds. Excellent grain quality and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे गव्हाचे बियाणे. दर्जेदार दाणे आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 82)),
        companyCity: 'दिल्ली',
        minOrder: 5,
        packWeight: 20.0,
      ),
      Product(
        id: 'SP083',
        name: 'JAWAS KSSN-101 2KG',
        nameMr: 'जवस केएसएसएन-१०१ २किलो',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Jawari',
        packSize: '2KG',
        price: 480.0,
        imageUrl: '',
        description: 'Premium quality Jowar seeds. High fodder yield and grain quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे ज्वारी बियाणे. चारा आणि धान्याचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 83)),
        companyCity: 'कर्नूल',
        minOrder: 5,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP084',
        name: 'JAWAS KSSN-188 2KG',
        nameMr: 'जवस केएसएसएन-१८८ २किलो',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Jawari',
        packSize: '2KG',
        price: 480.0,
        imageUrl: '',
        description: 'Premium quality Jowar seeds. High fodder yield and grain quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे ज्वारी बियाणे. चारा आणि धान्याचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 84)),
        companyCity: 'कर्नूल',
        minOrder: 5,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP085',
        name: 'JAWAS KSSN-195 2KG',
        nameMr: 'जवस केएसएसएन-१९५ २किलो',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Jawari',
        packSize: '2KG',
        price: 480.0,
        imageUrl: '',
        description: 'Premium quality Jowar seeds. High fodder yield and grain quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे ज्वारी बियाणे. चारा आणि धान्याचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 85)),
        companyCity: 'कर्नूल',
        minOrder: 5,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP086',
        name: 'MAIZE SMGH-09 BG-II/KOSCO/ 5.0KG',
        nameMr: 'मका एसएमजीएच-०९ बीजी-२/कोस्को/ ५.०किलो',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Maize',
        packSize: '5KG',
        price: 1100.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 86)),
        companyCity: 'कर्नूल',
        minOrder: 5,
        packWeight: 5.0,
      ),
      Product(
        id: 'SP087',
        name: 'SOMESH BG-II 09 (KOSCO) 500GM',
        nameMr: 'सोमेश बीजी-२ ०९ (कोस्को) ५००ग्रॅम',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '500GM',
        price: 3600.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 87)),
        companyCity: 'कर्नूल',
        minOrder: 1,
        packWeight: 0.5,
      ),
      Product(
        id: 'SP088',
        name: 'TUV MEGHAM LCG-5355 2KG',
        nameMr: 'तूर मेघम एलसीजी-५३५५ २किलो',
        brand: 'Kurnool Seeds',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 480.0,
        imageUrl: '',
        description: 'Premium quality Tur seeds. High branching type with excellent grain weight.',
        descriptionMr: 'दर्जेदार तूर बियाणे. जास्त फांद्या फुटणारे आणि टपोऱ्या दाण्यांचे बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 88)),
        companyCity: 'कर्नूल',
        minOrder: 30,
        packWeight: 2.0,
      ),
      Product(
        id: 'SP089',
        name: 'F-MAIZE BALWAN (PALMOOR) 4 KG',
        nameMr: 'मका बलवान (पालमोर) ४ किलो',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Maize',
        packSize: '4KG',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 89)),
        companyCity: 'हैद्राबाद',
        minOrder: 5,
        packWeight: 4.0,
      ),
      Product(
        id: 'SP090',
        name: 'F-MAIZE GOLDY (PALMOOR) 4KG',
        nameMr: 'मका गोल्डी (पालमोर) ४किलो',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Maize',
        packSize: '4KG',
        price: 880.0,
        imageUrl: '',
        description: 'High yielding hybrid Maize seeds. Excellent cob size and grain density.',
        descriptionMr: 'उत्कृष्ट प्रतिचे मका बियाणे. मोकळे आणि टपोरे दाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 90)),
        companyCity: 'हैद्राबाद',
        minOrder: 5,
        packWeight: 4.0,
      ),
      Product(
        id: 'SP091',
        name: 'FODDER GOLD-44 (GG) 3KG',
        nameMr: 'चारा गोल्ड-४४ (जीजी) ३किलो',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Fodder',
        packSize: '3KG',
        price: 420.0,
        imageUrl: '',
        description: 'High nutritional value Fodder seeds. Excellent regrowth and biomass.',
        descriptionMr: 'पोषक गुणांनी समृद्ध चारा बियाणे. जलद वाढ आणि दर्जेदार चारा.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 91)),
        companyCity: 'हैद्राबाद',
        minOrder: 5,
        packWeight: 3.0,
      ),
      Product(
        id: 'SP092',
        name: 'JOWAR BG-V (PALMOOR) 400GM',
        nameMr: 'ज्वारी बीजी-व्ही (पालमूर) ४००ग्रॅम',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Jawari',
        packSize: '400GM',
        price: 180.0,
        imageUrl: '',
        description: 'Premium quality Jowar seeds. High fodder yield and grain quality.',
        descriptionMr: 'उत्कृष्ट प्रतिचे ज्वारी बियाणे. चारा आणि धान्याचे उत्तम उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 92)),
        companyCity: 'हैद्राबाद',
        minOrder: 10,
        packWeight: 0.4,
      ),
      Product(
        id: 'SP093',
        name: 'SAMRUDHI PLH-44 BG-II 475 GM',
        nameMr: 'समृद्धी पीएलएच-४४ बीजी-२ ४७५ ग्रॅम',
        brand: 'Palmoor Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 850.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 93)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP094',
        name: 'CYRUS PRCH-122 BG-II [PRAVARDHAN] 475GM',
        nameMr: 'सायकल पीआरसीएच-१२२ बीजी-२ [प्रवर्धन] ४७५ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 860.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 94)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP095',
        name: 'PUSHPA PRCH-505 BG-II [PRAVARDHAN] 475GM',
        nameMr: 'पुष्पा पीआरसीएच-५०५ बीजी-२ [प्रवर्धन] ४७५ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 860.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 95)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP096',
        name: 'SHANI PRCH-333 BG-II [PRAVARDHAN] 475 GM',
        nameMr: 'शनी पीआरसीएच-३३३ बीजी-२ [प्रवर्धन] ४७५ ग्रॅम',
        brand: 'Pravardhan Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 860.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 96)),
        companyCity: 'हैद्राबाद',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP097',
        name: 'AASHISH BG-II (RHD286) COTTON 475 GM',
        nameMr: 'आशिष बीजी-२ (आरएचडी२८६) कापूस ४७५ ग्रॅम',
        brand: 'Rallies Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 890.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 97)),
        companyCity: 'मुंबई',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP098',
        name: 'AJODHA BG-II COTTON [RHD28] 475GMS',
        nameMr: 'अयोध्या बीजी-२ कापूस [आरएचडी२८] ४७५ग्रॅम',
        brand: 'Rallies Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 880.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 98)),
        companyCity: 'मुंबई',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP099',
        name: 'RIHAN BG-II (RHD343) COTTON 475GMS',
        nameMr: 'रिहान बीजी-२ (आरएचडी३४३) कापूस ४७५ग्रॅम',
        brand: 'Rallies Seeds',
        category: 'Seeds',
        cropType: 'Cotton',
        packSize: '475GM',
        price: 890.0,
        imageUrl: '',
        description: 'High yielding BG-II cotton seeds. Excellent boll retention and disease resistance.',
        descriptionMr: 'उत्कृष्ट प्रतिचे कापूस बियाणे. भरपूर उत्पादन आणि रोग प्रतिकारक क्षमता.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 99)),
        companyCity: 'मुंबई',
        minOrder: 30,
        packWeight: 0.475,
      ),
      Product(
        id: 'SP100',
        name: 'SOYABEAN KDS726 C/F 30 KG',
        nameMr: 'सोयाबीन केडीएस७२६ सी/एफ ३० किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 2600.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 100)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP101',
        name: 'SOYABEAN KDS753 I.L. 30 KG',
        nameMr: 'सोयाबीन केडीएस७५३ आय.एल. ३० किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 2600.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 101)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP102',
        name: 'SOYABEAN KDS-992 C/F 30 KG',
        nameMr: 'सोयाबीन केडीएस-९९२ सी/एफ ३० किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '30KG',
        price: 2650.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 102)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 30.0,
      ),
      Product(
        id: 'SP103',
        name: 'SOYABEAN M-612 Y.L. 25 KG',
        nameMr: 'सोयाबीन एम-६१२ वाय.एल. २५ किलो',
        brand: 'Rushikesh Seeds',
        category: 'Seeds',
        cropType: 'Soybean',
        packSize: '25KG',
        price: 2500.0,
        imageUrl: '',
        description: 'High germination variety Soybean seeds. High oil content and excellent yield.',
        descriptionMr: 'उत्कृष्ट उगवण क्षमता असलेले सोयाबीन बियाणे. तेलाचे जास्त प्रमाण आणि भरपूर उत्पादन.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 103)),
        companyCity: 'बुलढाणा',
        minOrder: 1,
        packWeight: 25.0,
      ),
      Product(
        id: 'SP104',
        name: '18:18:10 [MARUTI] 50KG',
        nameMr: '१८:१८:१० [मारुती] ५०किलो',
        brand: 'Maruti',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 1350.0,
        imageUrl: '',
        description: 'Maruti mixed NPK complex fertilizer. Balanced nutrition with equal nitrogen and phosphorus ratios.',
        descriptionMr: 'मारुती मिश्रित एनपीके खत. समान नायट्रोजन आणि फॉस्फरस गुणोत्तरासह संतुलित पोषण.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 104)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP105',
        name: '20:20:00 [MAROTI] 50KG',
        nameMr: '२०:२०:०० [मारोती] ५०किलो',
        brand: 'Maruti',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 1400.0,
        imageUrl: '',
        description: 'Maroti mixed complex fertilizer. Rich in nitrogen and phosphorus nutrients for root growth.',
        descriptionMr: 'मारोती मिश्रित खत. नायट्रोजन आणि फॉस्फरसने समृद्ध खत.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 105)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP106',
        name: '18:18:10 [SHIVA] 50KG',
        nameMr: '१८:१८:१० [शिवा] ५०किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 1350.0,
        imageUrl: '',
        description: 'Shiva mixed NPK complex fertilizer. High grade plant nutrients.',
        descriptionMr: 'शिवा मिश्रित एनपीके संयुक्त खत. उच्च दर्जाची वनस्पती अन्नद्रव्ये.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 106)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP107',
        name: '20:20:0 [SHIVA] 50 KG',
        nameMr: '२०:२०:० [शिवा] ५० किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 1400.0,
        imageUrl: '',
        description: 'Shiva mixed complex fertilizer. High analysis nitrogen and phosphorus fertilizer.',
        descriptionMr: 'शिवा मिश्रित संयुक्त खत. उच्च दर्जाचे नायट्रोजन आणि फॉस्फरस खत.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 107)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP108',
        name: 'SUPER PHOSPHATE BORONATED DANEDAR [SHIVA] 50KG',
        nameMr: 'सुपर फॉस्फेट बोरॉनयुक्त दाणेदार [शिवा] ५०किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 780.0,
        imageUrl: '',
        description: 'Boronated Single Super Phosphate Granular fertilizer by Shiva. Enriched with boron.',
        descriptionMr: 'शिवा सिंगल सुपर फॉस्फेट बोरॉनयुक्त दाणेदार खत. बोरॉनने समृद्ध.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 108)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP109',
        name: 'SUPER PHOSPHATE DANEDAR [SHIVA] 50KG',
        nameMr: 'सुपर फॉस्फेट दाणेदार [शिवा] ५०किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 650.0,
        imageUrl: '',
        description: 'Single Super Phosphate Granular fertilizer by Shiva. High solubility phosphorus.',
        descriptionMr: 'शिवा सिंगल सुपर फॉस्फेट दाणेदार खत. उच्च विद्राव्य फॉस्फरस.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 109)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP110',
        name: 'SUPER PHOSPHATE POWDER [SHIVA] 50KG',
        nameMr: 'सुपर फॉस्फेट पावडर [शिवा] ५०किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Vegetable',
        packSize: '50KG',
        price: 600.0,
        imageUrl: '',
        description: 'Single Super Phosphate Powder fertilizer by Shiva. Easy absorption.',
        descriptionMr: 'शिवा सिंगल सुपर फॉस्फेट पावडर खत. जलद शोषण.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 110)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP111',
        name: 'SUPER PHOSPHATE ZINCATED [TRISHUL BRAND] 50 KG',
        nameMr: 'सुपर फॉस्फेट झिंकयुक्त [त्रिशूळ ब्रँड] ५० किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Cotton',
        packSize: '50KG',
        price: 700.0,
        imageUrl: '',
        description: 'Zincated Single Super Phosphate under Trishul Brand. Enriched with zinc micronutrients.',
        descriptionMr: 'त्रिशूळ ब्रँड झिंकयुक्त सिंगल सुपर फॉस्फेट. झिंकयुक्त सूक्ष्मद्रव्यांनी समृद्ध.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 111)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP112',
        name: 'ZINC+ BORON GRANULATED SHIVA GOLD 50KG',
        nameMr: 'झिंक+ बोरॉन दाणेदार शिवा गोल्ड ५०किलो',
        brand: 'Shiva Global',
        category: 'Fertilizers',
        cropType: 'Cotton',
        packSize: '50KG',
        price: 850.0,
        imageUrl: '',
        description: 'Zincated and Boronated Granular Shiva Gold fertilizer. Complete secondary nutrients.',
        descriptionMr: 'झिंक आणि बोरॉनयुक्त दाणेदार शिवा गोल्ड खत. पूर्ण दुय्यम अन्नद्रव्ये.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 112)),
        companyCity: 'कोल्हापूर',
        minOrder: 10,
        packWeight: 50.0,
      ),
      Product(
        id: 'SP113',
        name: 'TUV GOLD 48 (DAFTARI) 2KG',
        nameMr: 'तूर गोल्ड ४८ (दप्तरी) २किलो',
        brand: 'Daftari Agro',
        category: 'Seeds',
        cropType: 'Tur',
        packSize: '2KG',
        price: 240.0,
        imageUrl: '',
        description: 'Premium quality Tur seeds by Daftari.',
        descriptionMr: 'दप्तरी तर्फे उच्च दर्जाचे तूर बियाणे.',
        inStock: true,
        createdAt: now.subtract(const Duration(hours: 113)),
        companyCity: 'शेलू',
        minOrder: 20,
        packWeight: 2.0,
      ),





    ];
  }
}
